disabled_rules:
  - identifier_name
  - line_length
  - trailing_whitespace

opt_in_rules:
  - array_init
  - closure_spacing
  - contains_over_first_not_nil
  - empty_count
  - fatal_error_message
  - first_where
  - operator_usage_whitespace
  - sorted_first_last
  - sorted_imports

trailing_comma:
  mandatory_comma: true

excluded:
  - Pods

custom_rules:
  straight_quotes:
    included: "Localized.swift"
    name: "Straight Quotes"
    regex: "'|\""
    match_kinds:
      - docComment
    message: "Quotes and apostrophes in localized strings should be curly: “” ‘’"
    severity: warning
