# os: osx
osx_image: xcode10.2
language: swift
# install: true
script:
  - xcodebuild -workspace SwiftFest.xcworkspace -scheme "SwiftFest" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X,OS=12.1' build test | xcpretty -f `xcpretty-travis-formatter`
