# A list of devices you want to take the screenshots from
devices([
  "iPhone 8",
  "iPhone 8 Plus",
  "iPhone SE",
  "iPhone X",
  "iPad Pro (9.7-inch)",
  "iPad Pro (12.9-inch)",
  # "iPad Pro (10.5-inch)", # not supported in iTunes Connect
])

languages([
  "en-US",
])

ENV["FASTLANE_SNAPSHOT"] = "YES"

# The name of the scheme which contains the UI Tests
scheme "Screenshots"

configuration "Debug"

clear_previous_screenshots true
